name: CS Fixer

on:
  push:
  pull_request:
    paths:
      - "**.php"

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv

      - name: Install Dependencies
        run: composer install --prefer-dist

      - name: Fix Style
        run: ./vendor/bin/php-cs-fixer fix --diff --allow-risky=yes

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling changes
